- name: Create AWS instance
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  remote_user: mayank
  roles:
    - create

- name: Configure WebServer
  hosts: 127.0.0.1
  connection: webserver
  sudo: yes
  remote_user: mayank
  roles:
    - http
